#usage: ansible-playbook -i files/hosts deploy-cloudstack.yml -e server_id=1 -vvvv

--- 
- name: Set up cloudstack management server
  hosts: acs-manager
  remote_user: "{{remote_user}}"

  vars_files:
    - group_vars/all.yml
    - group_vars/management-server-vars.yml

  roles:
#    - env-preparation 
#    - mariadb
#    - nfs-server
#    - cloudstack-manager
#    - cloudstack-agent
    - cloudmonkey

#  tasks: 
#    - include: ./roles/cloudstack-manager/tasks/seedstorage.yml
