#usage: ansible-playbook -i files/hosts deploy-cloudstack.yml -e server_id=1 -vvvv

--- 
- name: Set up cloudstack management server
  hosts: acs-manager
  remote_user: "{{remote_user}}"

  vars_files:
    - group_vars/management-server-vars.yml

  roles:
#    - env-preparation 
    - mariadb
#    - nfs-server
#    - cloudstack-manager
#    - cloudmonkey
#    - cloudstack-agent
#    - openvswitch

#  tasks: 
#    - include: ./roles/cloudstack-manager/tasks/seedstorage.yml

#  vars: 
#    - mysql_root_password: Cl0ud5tack
#    - mysql_cloud_password: Cl0ud5tack
#    - baseurl_cloudstack: "http://cloudstack.apt-get.eu/centos/7/4.11/"
#    - old_mysql_root_password: ""
#    - systemvm_templates: 
#      - { url: 'http://cloudstack.apt-get.eu/systemvm/4.11/systemvmtemplate-4.11.1-kvm.qcow2.bz2', hypervisor: 'kvm' }
#      - { url: 'http://cloudstack.apt-get.eu/systemvm/4.11/systemvmtemplate-4.11.1-vmware.ova', hypervisor: 'vmware' }
#      - { url: 'http://cloudstack.apt-get.eu/systemvm/4.11//systemvmtemplate-4.11.1-xen.vhd.bz2', hypervisor: 'xenserver' }
