#usage: ansible-playbook -i files/hosts deploy-cloudstack.yml -e server_id=1 -vvvv

--- 
- name: Set up cloudstack management server
  hosts: jenkins-host
  remote_user: "{{remote_user}}"

  roles:
    - jenkins-installation
