#usage: ansible-playbook -i files/hosts deploy-cloudstack.yml -e server_id=1 -vvvv

--- 
- name: Set up cloudstack management server
  hosts: all-hosts
  remote_user: "{{remote_user}}"

  vars_files:
    - group_vars/all.yml

  tasks: 
    - name: install x2go sesssion server
      yum: name=x2goserver-xsession state=present
      become: yes
      become_method: sudo

    - name: install xfce
      yum:
        name: "@Xfce"
        state: present
      become: yes
      become_method: sudo

    - name: reboot host
      shell: reboot
      become: yes
      become_method: sudo
