# Copyright (C) ShapeBlue Ltd - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Released by ShapeBlue <info@shapeblue.com>, April 2014

---

- name: Upgrade all packages to latest version
  yum: 
    name: '*' 
    state: latest
  become: yes
  become_method: sudo 

- name: Add host to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{inventory_hostname}} {{management_server_name}}"
  become: yes
  become_method: sudo
