# Copyright (C) ShapeBlue Ltd - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Released by ShapeBlue <info@shapeblue.com>, April 2014

---

- name: Upgrade all packages to latest version
  yum: 
    name: '*' 
    state: latest
  become: yes
  become_method: sudo 

- name: Add host to hosts
  lineinfile:
    path: /etc/hosts
    line: "{{inventory_hostname}} {{management_server_name}}.{{cloud_domain}}"
  become: yes
  become_method: sudo

- name: Set hostname
  shell: hostnamectl set-hostname "{{management_server_name}}.{{cloud_domain}}"
  become: yes
  become_method: sudo

- name: Ensure ntp packages are installed
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - ntp
    - ansible
  become: yes
  become_method: sudo

- name: Ensure selinux python bindings are installed
  yum: name=libselinux-python state=present
  become: yes
  become_method: sudo
  
- name: Ensure the Apache Cloudstack Repo file is configured
  template: src=cloudstack.repo.j2 dest=/etc/yum.repos.d/cloudstack.repo
  become: yes
  become_method: sudo

- name: Ensure GPGKey is installed
  rpm_key: state=present key={{ item }}
  with_items:
    - http://packages.shapeblue.com/release.asc
  become: yes
  become_method: sudo

- name: Set selinux to permissive
  command: setenforce permissive
  changed_when: false
  become: yes
  become_method: sudo
  
- name: Ensure selinux is set permanently
  selinux: policy=targeted state=permissive
  become: yes
  become_method: sudo

