---

- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: Ensure MariaDB started
  service: name=mariadb state=started

- name: Modify suoders
  lineinfile:
    path: /etc/suoders
    line: Defaults:cloud !requiretty
  become: yes
  become_method: sudo

- name: Setup management Server
  shell: cloudstack-setup-management

- name: Install cfg
  shell: pip install ifcfg

- name: Upgrade pip
  yum: name = pip state = latest
  

- name: Openvswitch
  yum: 
  with_items:
    - python-pip
    - openvswitch.x86_64 
    - openvswitch-controller.x86_64 
    - NetworkManager-ovs


