---

- name: Ensure selinux python bindings are installed (Ansible requirement)
  yum: name=libselinux-python state=present

- name: Remove firewalld if present
  yum: name=firewalld state=absent

- name: Remove iptables if present
  yum: name=iptables state=absent

- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
#    - MariaDB-client
  become: yes
  become_method: sudo

- name: Configure MySQL my.cnf using Template
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: Ensure MariaDB started
  service: name=mariadb state=restarted
  become: yes
  become_method: sudo

- name: Ensure Mariadb service is started and set to start on boot
  service: name=mariadb state=started enabled=yes
  
- name: update mariadb root password
  mysql_user: user="root" password="{{ mysql_root_password }}" host="localhost" login_user="root" login_password="{{ old_mysql_root_password }}"


