# Copyright (C) ShapeBlue Ltd - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Released by ShapeBlue <info@shapeblue.com>, April 2014

---

- name: Ensure openvswitch is installed
  yum: name=openvswitch state=present

- name: Ensure openvswitch-controller is installed
  yum: name=openvswitch-controller state=present

- name: Replace default libvirtd configs with updated ones
  template: src=libvirtd.conf.j2 dest=/etc/libvirt/libvirtd.conf

- name: Restart the libvirtd service
  service: name=libvirtd state=restarted